### ISSUE TITLE
Issue with example code

### ISSUE THREAD

**Issue by benjamin-macadam** [SciML/NBodySimulator.jl#29]
I'm a bit confused - I tried running the example code for gravitational interaction and it didn't generate the expected animation.

**Comment by ChrisRackauckas** [comment]
Hey, what did it generate?

@SebastianM-C could you take a look?

**Comment by benjamin-macadam** [comment]
It just generated a static image - should I be using a specific backend for Plots?

**Comment by ChrisRackauckas** [comment]
Oh that I'm not sure about. 🤷 it's been years since I generated animations with Plots.jl. Maybe you might want to ask in the Slack plotting channel whether someone knows how that could give a static image.

**Comment by benjamin-macadam** [comment]
It's spitting out this warning, which could be related:

 Warning: Attribute alias `xlim` detected in the user recipe defined for the signature (::NBodySimulator.SimulationResult{PotentialNBodySystem{MassBody{Float64,Float64}}}, ::Float64). To ensure expected behavior it is recommended to use the default attribute `xlims`.
└ @ Plots ~/.juliapro/JuliaPro_v1.4.2-1/packages/Plots/3INZP/src/pipeline.jl:15
┌ Warning: Attribute alias `ylim` detected in the user recipe defined for the signature (::NBodySimulator.SimulationResult{PotentialNBodySystem{MassBody{Float64,Float64}}}, ::Float64). To ensure expected behavior it is recommended to use the default attribute `ylims`.

**Comment by SebastianM-C** [comment]
@ChrisRackauckas The plot recipe seems incomplete.
https://github.com/SciML/NBodySimulator.jl/blob/5fff46d3ccb617e230a2a9c5e70d9a7e2039be36/src/nbody_simulation_result.jl#L354-L366

In the case of a gravitational potential it only draws the orbits, which is why only a static image is generated.
I'll open a PR to add bodies as scatter plots.

**Comment by SebastianM-C** [comment]
@benjamin-macadam Can you try again on master? On my machine it now produces an animation close to the one in the README.

**Comment by ChrisRackauckas** [comment]
should be registered soon as v1.4

**Comment by benjamin-macadam** [comment]
That fixes it, thanks!
