### ISSUE TITLE
Non breaking typo

### ISSUE THREAD

**Issue by axla-io** [SciML/NBodySimulator.jl#72]
Seems to be a typo in:

https://github.com/SciML/NBodySimulator.jl/blob/fa8285c4001aba8a332ede949e042b1998d751e0/src/nbody_system.jl#L36-L54

i.e. `paramteres` should be `parameters`
This doesn't seem to impact the functionality of the code.

**Comment by ChrisRackauckas** [comment]
Hehe oops.
