### ISSUE TITLE
Integrator warning

### ISSUE THREAD

**Issue by astro-kevin** [SciML/NBodySimulator.jl#85]
> Warning: Interrupted. Larger maxiters is needed. If you are using an integrator for non-stiff ODEs or an automatic switching algorithm (the default), you may want to consider using a method for stiff equations. See the solver pages for more details (e.g. https://docs.sciml.ai/DiffEqDocs/stable/solvers/ode_solve/#Stiff-Problems).

**Comment by ChrisRackauckas** [comment]
Just increase `maxiters`. It's a keyword argument to `solve` as the warning states.

Closing as there's nothing to solve here, but feel free to ask more questions here or on discourse.julialang.org.

**Comment by astro-kevin** [comment]
Isn't that a kwarg to `solve`? I don't see where this package interfaces to that method. Where should I be passing it in?

**Comment by ChrisRackauckas** [comment]
`sim_result = run_simulation(simulation)` passes its kwargs on IIRC.
